import type { Metadata } from "next";
import { ReactNode } from "react";
import { Toaster } from "sonner";
import "../globals.css";

export const metadata: Metadata = {
  title: "tldraw editor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <main>{children}</main>
        <Toaster richColors position="top-center" />
      </body>
    </html>
  );
}
